--------------------------------------------------------
--  CREATE RELATIVE TABLES
--------------------------------------------------------

DROP TABLE "F_SALES";
DROP TABLE "D_PRODUCTS";
DROP TABLE "D_CUSTOMERS";
DROP TABLE "D_OUTLET";
DROP TABLE "D_SUPPLIERS";

CREATE TABLE D_PRODUCTS (
    PRODUCT_ID VARCHAR2(6)  NOT NULL PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(28)
);

CREATE TABLE D_CUSTOMERS (
    CUSTOMER_ID VARCHAR2(4)  NOT NULL PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(28),
    CUSTOMER_ACCOUNTTYPE VARCHAR2(1)
);

CREATE TABLE D_OUTLET (
    OUTLET_ID VARCHAR2(4)  NOT NULL PRIMARY KEY,
    OUTLET_NAME VARCHAR2(20)
);

CREATE TABLE D_SUPPLIERS (
    SUPPLIER_ID VARCHAR2(5)  NOT NULL PRIMARY KEY,
    SUPPLIER_NAME VARCHAR2(30)
);

CREATE TABLE F_SALES (
    DATASTREAM_ID NUMBER(8,0) NOT NULL PRIMARY KEY,
    PRODUCT_ID VARCHAR2(6) NOT NULL,
    CUSTOMER_ID VARCHAR2(4) NOT NULL,
    OUTLET_ID VARCHAR2(4) NOT NULL,
    SUPPLIER_ID  VARCHAR2(5) NOT NULL,
    D_DATE      DATE,
    QUANTITY_SOLD NUMBER(3,0),
    SALE_PRICE NUMBER(5,2),
    TOTAL_SALE  NUMBER(6,2)

);

ALTER TABLE F_SALES
ADD CONSTRAINT FK_PRODUCT
FOREIGN KEY (PRODUCT_ID) REFERENCES D_PRODUCTS(PRODUCT_ID);

ALTER TABLE F_SALES
ADD CONSTRAINT FK_CUSTOMER
FOREIGN KEY (CUSTOMER_ID) REFERENCES D_CUSTOMERS(CUSTOMER_ID);

ALTER TABLE F_SALES
ADD CONSTRAINT FK_OUTLET
FOREIGN KEY (OUTLET_ID) REFERENCES D_OUTLET(OUTLET_ID);

ALTER TABLE F_SALES
ADD CONSTRAINT FK_SUPPLIER
FOREIGN KEY (SUPPLIER_ID) REFERENCES D_SUPPLIERS(SUPPLIER_ID);

CREATE BITMAP INDEX PRODUCT_ID_IDX ON F_SALES(PRODUCT_ID);
CREATE BITMAP INDEX CUSTOMER_ID_IDX ON F_SALES(CUSTOMER_ID);
CREATE BITMAP INDEX OUTLET_ID_IDX ON F_SALES(OUTLET_ID);
CREATE BITMAP INDEX SUPPLIER_ID_IDX ON F_SALES(SUPPLIER_ID);

COMMIT;
